# Nome da aplicação
spring.application.name=estoquep

# Banco de dados H2 em memória
spring.datasource.url=jdbc:h2:mem:estoquepdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console web do H2 (para visualizar o banco no navegador)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração do Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Porta do servidor (opcional, 8080 já é o padrão)
server.port=8080